;================================================================================
; MultiLoad.s — EASYLOAD.PRG: Multi-Load Game Launcher Plugin (V2)
;================================================================================
;
; PURPOSE:
;   Plugin selected by the user from the EasySD menu when the user has
;   navigated to a game directory containing multi-load game files.
;   Installs a resident LOAD hook, loads the first game part, and jumps to it.
;   The game then runs normally; subsequent LOAD "FILE",8,x calls are
;   intercepted by the resident hook and served from the SD card.
;
; V2 CHANGES (from V1):
;   - Config block at $C003: ML_CONFIG_VERSION, ML_FIRST_PART_LEN,
;     ML_FIRST_PART_NAME (16 bytes, null-padded).  Patched by
;     Tools/create_multiload.py — no recompile needed per game.
;   - COMMAND_GET_PATH run after RL_INSTALL: stores game directory path at
;     RL_DIR_PATH ($E840) so the hook can chdir before every LOAD.
;   - ResidentLoader V2: RL_NMI_REDIRECT at $0368, SA=0 support,
;     RL_MINI_CARTLIB at $EA00 (no CartLib overwrite risk), chdir per LOAD.
;
; SD CARD LAYOUT EXPECTED (/MULTILOAD/ structure):
;   /MULTILOAD/TURRICAN/
;     EASYLOAD.PRG    ← this plugin (generated by create_multiload.py LOADER)
;     LOADER.PRG      ← ML_FIRST_PART_NAME = "LOADER"
;     LEVEL1.PRG      ← LOAD "LEVEL1",8,1 from game code
;     LEVEL2.PRG
;
; USAGE:
;   1. python Tools/build.py multiload        ← build template (once)
;   2. python Tools/create_multiload.py LOADER  ← patch config, outputs EASYLOAD.PRG
;   3. Copy EASYLOAD.PRG + game files to /MULTILOAD/GAMENAME/ on SD card
;   4. Navigate to /MULTILOAD/GAMENAME/ in EasySD menu, select EASYLOAD.PRG
;
; ENTRY POINT:  $C000 (standard plugin load address)
; EXIT:         JMP to game entry point (never returns to menu unless error)
;
; PROTOCOL INVARIANT:
;   ALL EasySD sessions MUST be closed with PROT_EndTalking on ALL exit paths.
;
; KNOWN LIMITATIONS (V2):
;   - LOAD calls that bypass $0330 via direct JSR $E16F cannot be intercepted.
;   - Game parts loading to $033C-$036F will overwrite the resident stub.
;   - LOAD with device != 8 is passed through to original Kernal vector.
;
; DEPENDENCIES:
;   ResidentLoader.s, CartLibStream.s (included at bottom)
;
; AUTHOR: Claude Sonnet 4.6 (Sprint 15 — V2)
; DATE: 2026-03-16
;================================================================================

; DEBUG mode - passed from command line (-D DEBUG=0 / -D DEBUG=1)
.include "../../DebugMacros.s"
.include "../../APIMacros.s"

;================================================================================
; Plugin entry — $C000
; Layout: JMP MAIN (3 bytes) then config block at $C003.
;================================================================================

	*=$C000
	JMP MAIN

;================================================================================
; Config block — $C003 to $C014
; Patched by Tools/create_multiload.py for each game.
; RL_ constants reference $C015+ (MAIN etc.) which follows this block.
;================================================================================

ML_CONFIG_VERSION:  .byte 2         ; $C003 — version sentinel, must be 2
ML_FIRST_PART_LEN:  .byte 0         ; $C004 — length of first-part name (patched)
ML_FIRST_PART_NAME: .fill 16, 0     ; $C005-$C014 — name, null-padded (patched)

;================================================================================
; MAIN — entry point ($C015)
;================================================================================

MAIN:
	JSR ML_SAVESTATE                ; save VIC/$01 for error-path restore

	; Install resident LOAD hook:
	;   copies RL_STUB image  → $033C (extended: saves X/Y, NMI redirect)
	;   copies RL_HANDLER+RL_MINI_CARTLIB → $E800-$EBFF
	;   writes RL_NMI_REDIRECT address ($0368) to $FFFA/$FFFB (RAM NMI vector)
	;   patches $0330/$0331 → RL_STUB ($033C)
	JSR RL_INSTALL

	; Start EasySD session
	; Arduino is in the game directory (user navigated there before selecting
	; EASYLOAD.PRG).  We immediately capture the path for chdir safety.
	JSR PROT_StartTalking

	;--- Capture current directory path into RL_DIR_PATH ($E840) ---
	; COMMAND_GET_PATH: Arduino sends dirFunc.currentPath (64 bytes) then
	; 192 zero bytes = 1 NMI page total.  We receive it at $E840.
	; Writes always reach RAM regardless of $01, so $E840 gets populated
	; even though $01=$37 (Kernal ROM is mapped there for reads).
	; This path is later read by RL_HANDLER under $01=$35 (Kernal RAM).
	LDA #COMMAND_GET_PATH
	JSR PROT_Send
	JSR PROT_WaitProcessing
	BCS ml_skip_path                ; skip on error — graceful degradation

	LDA #<RL_DIR_PATH               ; = $40 (low byte of $E840)
	STA ZP_IRQ_API_DATA_LO
	LDA #>RL_DIR_PATH               ; = $E8 (high byte of $E840)
	STA ZP_IRQ_API_DATA_HI
	LDA #1
	STA ZP_IRQ_API_DATA_LENGTH      ; 1 page = 256 bytes
	LDY #$00                        ; transfer mode x1 (CARTRIDGENMIHANDLERX1)
	JSR PROT_ReceiveFragmentNoCallback

ml_skip_path:
	;--- Load first game part ---
	; Name comes from config block ML_FIRST_PART_NAME, patched per game.
	LDA ML_FIRST_PART_LEN
	LDX #<ML_FIRST_PART_NAME
	LDY #>ML_FIRST_PART_NAME
	JSR PROT_SetName
	LDX #$01                        ; flags = read
	JSR PROT_OpenFile
	BCC ml_opened
	JMP MAIN_ERROR

ml_opened:
	; Get file info (size)
	#GETFILEINFO ML_FILEINFO_BUF
	BCS MAIN_ERROR

	; Store 32-bit file size
	LDA ML_FILEINFO_BUF + 28
	STA ZP_LOADFILE_API_SIZE0
	LDA ML_FILEINFO_BUF + 29
	STA ZP_LOADFILE_API_SIZE1
	LDA ML_FILEINFO_BUF + 30
	STA ZP_LOADFILE_API_SIZE2
	LDA ML_FILEINFO_BUF + 31
	STA ZP_LOADFILE_API_SIZE3

	; Read first page to ML_HDRBUF: 2-byte PRG header + up to 254 data bytes
	LDA #<ML_HDRBUF
	STA ZP_IRQ_API_DATA_LO
	LDA #>ML_HDRBUF
	STA ZP_IRQ_API_DATA_HI
	LDA #1
	STA ZP_IRQ_API_DATA_LENGTH
	LDY #$00
	JSR PROT_ReadFileNoCallback
	BCS MAIN_ERROR

	; ML_HDRBUF[0..1] = PRG load address (little-endian)
	; ML_HDRBUF[2..255] = first 254 bytes of program data

	LDA ML_HDRBUF
	STA $8B                         ; load address lo
	LDA ML_HDRBUF + 1
	STA $8C                         ; load address hi

	; Branch on file size
	LDA ZP_LOADFILE_API_SIZE1
	BNE ml_big_first

	; Small first part (size <= 255 bytes): copy (SIZE-2) data bytes only
	SEC
	LDA ZP_LOADFILE_API_SIZE0
	SBC #2
	BCC ml_close                    ; SIZE < 2 (header only)
	BEQ ml_close                    ; SIZE = 2 (header only, no data)
	TAX
	LDY #0
ml_copy_small:
	LDA ML_HDRBUF + 2, Y
	STA ($8B), Y
	INY
	DEX
	BNE ml_copy_small
	JMP ml_close

ml_big_first:
	; Large first part: copy first 254 data bytes, load rest via LoadFileBySize
	LDY #0
ml_copy_254:
	LDA ML_HDRBUF + 2, Y
	STA ($8B), Y
	INY
	CPY #254
	BNE ml_copy_254

	; Setup LoadFileBySize: target = load_addr+254, skip = 256 (already read)
	CLC
	LDA ML_HDRBUF
	ADC #254
	STA ZP_IRQ_API_DATA_LO
	LDA ML_HDRBUF + 1
	ADC #0
	STA ZP_IRQ_API_DATA_HI

	LDA #$00
	STA ZP_LOADFILE_API_SKIP_LO     ; skip = $0100 = 256
	LDA #$01
	STA ZP_LOADFILE_API_SKIP_HI

	JSR LoadFileBySize
	BCS MAIN_ERROR

ml_close:
	JSR PROT_CloseFile
	JSR PROT_EndTalking

	; Refresh load address pointer ($8B/$8C may be stale after copy loops)
	LDA ML_HDRBUF
	STA $8B
	LDA ML_HDRBUF + 1
	STA $8C

	; Jump to game — resident hook handles all future LOAD "...",8,x calls
	JMP ($008B)

;================================================================================
; Error path: end EasySD session, restore state, return to menu
;================================================================================

MAIN_ERROR:
	JSR PROT_EndTalking
ML_EXIT_TO_MENU:
	JSR ML_RESTORESTATE
	JSR PROT_ExitToMenu
	JMP *                           ; unreachable

;================================================================================
; ML_SAVESTATE / ML_RESTORESTATE — minimal VIC/$01 save for error path
;================================================================================

ML_SAVED_01:   .byte $37
ML_SAVED_D011: .byte $3B

ML_SAVESTATE:
	LDA PROCESSOR_PORT
	STA ML_SAVED_01
	LDA VIC_CONTROL_1
	STA ML_SAVED_D011
	RTS

ML_RESTORESTATE:
	LDA #$37                        ; ensure I/O visible before accessing $D011
	STA PROCESSOR_PORT
	LDA ML_SAVED_D011
	STA VIC_CONTROL_1
	LDA ML_SAVED_01
	STA PROCESSOR_PORT
	RTS

;================================================================================
; Data areas (in $C000 plugin space — always-accessible RAM)
;================================================================================

ML_FILEINFO_BUF: .fill 32          ; FAT directory entry (32 bytes)
ML_HDRBUF:       .fill 256         ; first-page read buffer (PRG header + data)

;================================================================================
; ResidentLoader code (stub image, handler image + mini-CartLib, RL_INSTALL)
; Included here so it is part of the plugin binary.
; Must come BEFORE CartLibStream.s so forward references in handler image work.
;================================================================================
.include "../../ResidentLoader.s"

;================================================================================
; CartLib (full chain: CartLibStream → CartLibHi → CartLib → CartLibCommon)
; Included AFTER ResidentLoader so all forward references resolve correctly.
;================================================================================
.include "../../CartLibStream.s"

;================================================================================
; Overflow guard — plugin must not reach I/O space
;================================================================================
.if * > $DF00
	.error "MultiLoad plugin overflow: exceeds $DF00 (I/O space)"
.endif
