#ifndef _IRQHACK64_
#include <avr/pgmspace.h>


#define _IRQHACK64_

#define TYPE_MENU 0
#define TYPE_STANDARD_PRG 1
#define TYPE_CARTRIDGE 2

#define CALLER_HANDLES_DIRECTORIES

// Auto-generated by build.py.
#include "BuildConfig.h"

#define USERAMLAUNCHER


#endif
